spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database: postgresql
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    open-in-view: false
    generate-ddl: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    "[org.springframework]": INFO
    "[org.hibernate]": INFO
